name: .NET Core

on:
  push:
    branches: 
    - master
    - release/*

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        framework: ['netcoreapp2.2', 'netcoreapp3.1']
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.208
    - name: Build with netcoreapp
      run: dotnet build --configuration Release --framework ${{ matrix.framework }}
  test:
    needs: [build]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        framework: ['netcoreapp2.2', 'netcoreapp3.1']
    steps:
      - name: Unit Testing
        run: dotnet test src --configuration Release --framework ${{ matrix.framework }} --list-tests
        
